# Generated by Django 4.2 on 2025-11-29 13:19

from django.db import migrations, models


def set_postgresql_default(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE volunteers_volunteer '
            'ALTER COLUMN email_confirmed SET DEFAULT FALSE;'
        )


def drop_postgresql_default(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE volunteers_volunteer '
            'ALTER COLUMN email_confirmed DROP DEFAULT;'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0005_volunteer_language_volunteer_privacy"),
    ]
    operations = [
        migrations.RunPython(
            set_postgresql_default,
            drop_postgresql_default,
        ),
    ]
