# Generated by Django 4.2 on 2026-03-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_populate_info_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
    ]
