# Generated by Django 4.2 on 2026-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_alter_task_edition_alter_track_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='tshirt_size',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], help_text='Volunteer t-shirt size (European sizing). As the shirt is worn over clothing, consider choosing one size up from your usual size.', max_length=4, null=True, verbose_name='T-shirt size'),
        ),
    ]
