# Generated by Django 4.2 on 2026-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_volunteer_tshirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Your preferred pronouns (e.g. she/her, he/him, they/them). Optional.', max_length=50, null=True, verbose_name='Pronouns'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='spoken_languages',
            field=models.ManyToManyField(blank=True, through='volunteers.VolunteerLanguage', to='volunteers.language'),
        ),
    ]
