# Generated by Django 4.2 on 2026-08-26 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteers', '0011_volunteer_pronouns_spoken_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.edition')),
                ('printed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_prints_made', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_prints', to='volunteers.volunteer')),
            ],
            options={
                'verbose_name': 'Label Print Log',
                'verbose_name_plural': 'Label Print Logs',
                'ordering': ['-printed_at'],
            },
        ),
    ]
