# Generated by Django 4.2 on 2026-08-26 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteers', '0012_add_labelprintlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requires_approval',
            field=models.BooleanField(blank=True, default=None, help_text='Override template setting. Leave blank to inherit from template.', null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='If set, volunteer sign-ups require approval from the task responsible.'),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Approval'), ('denied', 'Denied')], default='approved', max_length=10),
        ),
    ]
