# Generated by Django 4.2 on 2026-08-26 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteers', '0013_task_signup_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='enable_task_signin',
            field=models.BooleanField(default=False, help_text='Enable task sign-in/sign-out tracking for this edition.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.CreateModel(
            name='TaskAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_in_at', models.DateTimeField(blank=True, null=True)),
                ('signed_out_at', models.DateTimeField(blank=True, null=True)),
                ('signin_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('signout_link_sent_at', models.DateTimeField(blank=True, null=True)),
                ('manually_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marks', to=settings.AUTH_USER_MODEL)),
                ('volunteer_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='volunteers.volunteertask')),
            ],
            options={
                'verbose_name': 'Task Attendance',
                'verbose_name_plural': 'Task Attendances',
            },
        ),
    ]
