# Generated by Django 4.2 on 2026-08-31 20:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0014_task_signin_attendance'),
    ]

    operations = [
        # Step 1: add nullable (no unique constraint yet)
        migrations.AddField(
            model_name='taskattendance',
            name='signout_token',
            field=models.UUIDField(null=True, blank=True),
        ),
        # Step 2: populate unique UUIDs for existing rows
        migrations.RunSQL(
            sql="UPDATE volunteers_taskattendance SET signout_token = lower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-4' || substr(hex(randomblob(2)),2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(hex(randomblob(2)),2) || '-' || hex(randomblob(6))) WHERE signout_token IS NULL;",
            reverse_sql="UPDATE volunteers_taskattendance SET signout_token = NULL;",
        ),
        # Step 3: make it non-null and unique
        migrations.AlterField(
            model_name='taskattendance',
            name='signout_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
    ]
