# Generated by Django 4.2 on 2026-08-31 20:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_signout_tokens(apps, schema_editor):
    TaskAttendance = apps.get_model('volunteers', 'TaskAttendance')
    db_alias = schema_editor.connection.alias
    attendances = TaskAttendance.objects.using(db_alias).filter(
        signout_token__isnull=True
    )
    for attendance in attendances.iterator():
        attendance.signout_token = uuid.uuid4()
        attendance.save(using=db_alias, update_fields=['signout_token'])


def clear_signout_tokens(apps, schema_editor):
    TaskAttendance = apps.get_model('volunteers', 'TaskAttendance')
    TaskAttendance.objects.using(schema_editor.connection.alias).update(
        signout_token=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0014_task_signin_attendance'),
    ]

    operations = [
        # Step 1: add nullable (no unique constraint yet)
        migrations.AddField(
            model_name='taskattendance',
            name='signout_token',
            field=models.UUIDField(null=True, blank=True),
        ),
        # Step 2: populate unique UUIDs for existing rows
        migrations.RunPython(
            populate_signout_tokens,
            clear_signout_tokens,
        ),
        # Step 3: make it non-null and unique
        migrations.AlterField(
            model_name='taskattendance',
            name='signout_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
    ]
