# Generated by Django 4.2 on 2026-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0015_add_signout_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
