# Generated by Django 4.2 on 2026-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0016_add_language_native_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='privacy_policy_version',
            field=models.PositiveIntegerField(default=1, help_text='Version of the privacy policy this volunteer last accepted.'),
        ),
    ]
