# Generated by Django 4.2 on 2026-09-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0017_add_privacy_policy_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('building', models.CharField(blank=True, help_text="Building code, e.g. 'H', 'K', 'AW', 'U'.", max_length=50, null=True)),
                ('nav_slug', models.SlugField(blank=True, help_text="Slug used on nav.fosdem.org, e.g. 'janson' for https://nav.fosdem.org/l/janson/. Leave blank if this location isn't a mappable room.", max_length=100, null=True)),
                ('notes', models.CharField(blank=True, help_text='Optional free-text note, e.g. why no map link exists.', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='location_ref',
            field=models.ForeignKey(blank=True, help_text="Resolved Location matching the 'location' text, used for the nav.fosdem.org map link.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.location'),
        ),
        migrations.AddField(
            model_name='task',
            name='location_ref',
            field=models.ForeignKey(blank=True, help_text="Resolved Location matching the 'location' text, used for the nav.fosdem.org map link.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteers.location'),
        ),
    ]
