# Generated by Django 4.2 on 2026-09-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0020_seed_known_nav_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='private_staff_notes',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='private_staff_rating',
        ),
    ]
