# Generated by Django 5.2.17 on 2026-09-17 08:01

import django.db.models.deletion
import volunteers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0023_runner_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edition',
            field=models.ForeignKey(default=volunteers.models.current_edition_id, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='track',
            name='edition',
            field=models.ForeignKey(default=volunteers.models.current_edition_id, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
        migrations.AlterField(
            model_name='volunteerstatus',
            name='edition',
            field=models.ForeignKey(default=volunteers.models.current_edition_id, on_delete=django.db.models.deletion.PROTECT, to='volunteers.edition'),
        ),
    ]
